---
- name: installing tomcat
  hosts: all
  become: yes
  tasks:
    - name: install openjdk
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: add tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: add tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: download the tomacat file
      ansible.builtin.unarchive:
        src: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.5/bin/apache-tomcat-10.1.5.tar.gz
        remote_src: yes
        dest: /opt/tomcat
    - name: creat symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.5
        dest: /opt/tomcat/latest
        group: tomcat
        owner: tomcat
        state: link
    - name: change tomcat owner
      ansible.builtin.file:
        name: tomcat
        path: /opt/tomcat
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat
    - name: adding execution permissions to tomcat .sh file
      ansible.builtin.file:
        path: /opt/tomcat/latest/bin/*.sh
        mode: +x
        